// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reminder.Api.Data;

#nullable disable

namespace Reminder.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420142340_AddWeeklyDaysMask")]
    partial class AddWeeklyDaysMask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reminder.Api.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DailyMinuteOfDay")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OneTimeDueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScheduleKind")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyDaysMask")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Reminder.Api.Entities.ReminderOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReminderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("ReminderId", "CheckedAtUtc");

                    b.ToTable("reminder_occurrences", (string)null);
                });

            modelBuilder.Entity("Reminder.Api.Entities.ReminderOccurrence", b =>
                {
                    b.HasOne("Reminder.Api.Entities.Reminder", "Reminder")
                        .WithMany("Occurrences")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("Reminder.Api.Entities.Reminder", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
